version: '3.7'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80

  php:
    build: ./docker/php
    volumes:
      - ./:/php:cached

  pgsql:
    build: ./docker/pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgsql/pgdata:/var/lib/postgresql/data
